"""foreign key contraint error

Revision ID: 2e42bd24aa12
Revises: 170580300c66
Create Date: 2024-05-02 21:04:17.603454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e42bd24aa12'
down_revision: Union[str, None] = '170580300c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friend_user_id_fkey', 'friend', type_='foreignkey')
    op.drop_constraint('friend_friend_id_fkey', 'friend', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('friend_friend_id_fkey', 'friend', 'users', ['friend_id'], ['id'])
    op.create_foreign_key('friend_user_id_fkey', 'friend', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
